python train_hcrafter_env_modular.py \
--env=HomeostaticCrafter-v1 \
--experiment=modular_Aug27_1M \
--stats_avg=100 \
--num_envs_per_worker=2 \
--with_wandb=False \
--wandb_user=pakhibanchalia2418 \
--wandb_project=homeostatic_crafter_modular \
--wandb_group=no_maxgrad_norm \
--gamma=0.995 \
--train_for_env_steps=1000000 \
--batch_size=1024 \
